# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wiper < Formula
  desc ""
  homepage "https://github.com/steffakasid/wiper"
  version "0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/wiper/releases/download/v0.1/wiper_0.1_darwin_amd64.tar.gz"
      sha256 "74278e8bc66cb4ac0d03c71d0fd3b917da80a4214149da9c5f8c460749c22e1d"

      def install
        bin.install "wiper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/wiper/releases/download/v0.1/wiper_0.1_darwin_arm64.tar.gz"
      sha256 "19513811be24766a8c68559815ead21b0b851fe40ea7b90459c4c176cc613103"

      def install
        bin.install "wiper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/wiper/releases/download/v0.1/wiper_0.1_linux_amd64.tar.gz"
      sha256 "eb36d6d7290c91146cf7572e73b4b709c4daa8239d23f630e0af370f0cd76f96"

      def install
        bin.install "wiper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/wiper/releases/download/v0.1/wiper_0.1_linux_arm64.tar.gz"
      sha256 "8c5875d4ac6c74ec6db00c0ea6ccbf52c439e6c7115b6221247542564aa127f3"

      def install
        bin.install "wiper"
      end
    end
  end
end
