# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wiper < Formula
  desc ""
  homepage "https://github.com/steffakasid/wiper"
  version "0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/wiper/releases/download/v0.8/wiper_0.8_darwin_amd64.tar.gz"
      sha256 "22359bdceae8f62d93c04268f54099121478f901690329e5d8a44247bfb5b3a6"

      def install
        bin.install "wiper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/wiper/releases/download/v0.8/wiper_0.8_darwin_arm64.tar.gz"
      sha256 "f5e53cedb7bfa86726a865679c7dd33e885f2830496d6f9aee8ab511983ad552"

      def install
        bin.install "wiper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/wiper/releases/download/v0.8/wiper_0.8_linux_amd64.tar.gz"
        sha256 "72496998c17322a983b6b2ee2b9b79ff0f56e477050ea48331c5eb17c4c0e786"

        def install
          bin.install "wiper"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/wiper/releases/download/v0.8/wiper_0.8_linux_arm64.tar.gz"
        sha256 "24efd612b447239b1fba81b5d0093624bab6b1c413b320869e2496aa9bb825f8"

        def install
          bin.install "wiper"
        end
      end
    end
  end
end
