# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wiper < Formula
  desc ""
  homepage "https://github.com/steffakasid/wiper"
  version "0.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/wiper/releases/download/v0.10/wiper_0.10_darwin_amd64.tar.gz"
      sha256 "6e8932c50189fb87009f57b637ad9dc55cf2b895138c5d00cedd69e4a5f5bd81"

      def install
        bin.install "wiper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/wiper/releases/download/v0.10/wiper_0.10_darwin_arm64.tar.gz"
      sha256 "cfaf9cd4a7e7acc103e057e5ca8e57b559c591a6fdcec231489be63d456d7f84"

      def install
        bin.install "wiper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/wiper/releases/download/v0.10/wiper_0.10_linux_amd64.tar.gz"
      sha256 "2e6ef7d8bdefdc1ba7b7cd01a5c95545f145d2ccad4d19a4d50d6a5c93101b61"
      def install
        bin.install "wiper"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/wiper/releases/download/v0.10/wiper_0.10_linux_arm64.tar.gz"
      sha256 "41fc22194b85f061c2cc86e5faf4247785d1f692e5562fc2520e0cfed579e554"
      def install
        bin.install "wiper"
      end
    end
  end
end
